begin;
select plan(22);

create temporary table fixture(id uuid);
insert into fixture select (public.register_attendance_device('reliability-device','test',repeat('e',64),'soton-attendance-'||repeat('e',40))->>'deviceId')::uuid;
select is(public.register_attendance_device('reliability-device','collision',repeat('f',64),'soton-attendance-'||repeat('f',40))->>'error','device_identifier_exists','registration collision is rejected');
select is((select auth_token_hash from public.devices where id=(select id from fixture)),repeat('e',64),'collision preserves credentials');
select is((public.register_attendance_device('reliability-device','replay',repeat('e',64),'soton-attendance-'||repeat('f',40))->>'deviceId')::uuid,(select id from fixture),'same durable ownership proof replays registration');
select is((select count(*)::integer from public.push_subscriptions where device_id=(select id from fixture)),1,'registration replay retains original topic');
create temporary table snapshot(rows jsonb,prefs jsonb);
insert into snapshot values('[{"course_code":"COMP1311","course_name":"COMP1311","weekday":1,"start_time":"09:00","end_time":"10:00","form_url":"https://forms.office.com/r/test","timezone":"Asia/Kuala_Lumpur","enabled":true,"automation_ready":true,"exceptions":["2026-10-05"]}]','{"timezone":"Asia/Kuala_Lumpur","reminder_time":"19:30","reminders_enabled":true,"success_notifications_enabled":true}');
select is(public.replace_attendance_schedules((select id from fixture),2,(select rows from snapshot),(select prefs from snapshot))->>'ok','true','snapshot committed');
select throws_ok($q$select public.replace_attendance_schedules((select id from fixture),3,(select rows || rows from snapshot),(select prefs from snapshot))$q$,'23505',null,'duplicate insert rolls back delete');
select is((select count(*)::integer from public.schedules where device_id=(select id from fixture)),1,'last snapshot retained after insert failure');
select is((select schedule_version::integer from public.devices where id=(select id from fixture)),2,'failed replace does not advance version');
select is(public.replace_attendance_schedules((select id from fixture),1,'[]',(select prefs from snapshot))->>'stale','true','older version cannot overwrite latest snapshot');
select is(public.enqueue_attendance_reminders('2026-10-05'),0,'cancelled class creates no reminder');
select is(public.enqueue_attendance_reminders('2026-10-12'),1,'ready class creates reminder');
select is(public.enqueue_attendance_reminders('2026-10-12'),0,'same reminder is idempotent');
select public.record_attendance_event((select id from fixture),'{"occurrence_key":"one","course_code":"COMP1311","class_date":"2026-10-01","start_time":"09:00","end_time":"10:00","status":"unknown"}');
select public.record_attendance_event((select id from fixture),'{"occurrence_key":"one","course_code":"COMP1311","class_date":"2026-10-01","status":"unknown"}');
select is((select count(*)::integer from public.attendance_logs where device_id=(select id from fixture)),1,'event idempotent');
select is((select count(*)::integer from public.notification_outbox where device_id=(select id from fixture) and logical_key='event:one'),1,'event outbox idempotent');
create temporary table claims as select * from public.claim_attendance_notifications(100);
select is((select count(*)::integer from public.claim_attendance_notifications(100)),0,'live claimed rows unavailable to another worker');
select is(public.finish_attendance_notification((select id from claims limit 1),gen_random_uuid(),'accepted'),false,'wrong lease cannot update row');
select is(public.finish_attendance_notification((select id from claims limit 1),(select lease_token from claims limit 1),'accepted'),true,'owner lease records acceptance');
select ok((select provider_accepted_at is not null and phone_receipt_confirmed_at is null from public.notification_outbox where id=(select id from claims limit 1)),'acceptance does not assert phone receipt');
update public.notification_outbox set lease_until=now()-interval '1 second' where delivery_state='sending';
select count(*) from public.claim_attendance_notifications(100);
select ok(not exists(select 1 from public.notification_outbox where delivery_state='sending'),'expired sender is quarantined');
select ok(exists(select 1 from public.notification_outbox where delivery_state='uncertain' and discarded_at is not null),'crashed send retains uncertainty');
select ok(not has_function_privilege('authenticated','public.claim_attendance_notifications(integer)','execute'),'ordinary users cannot claim global work');
select ok(not has_function_privilege('anon','public.replace_attendance_schedules(uuid,bigint,jsonb,jsonb)','execute'),'anonymous callers cannot replace snapshots');
select * from finish();
rollback;
