const copy={
  zh:{
    documentTitle:'Attendance · 自动打卡设置',appTitle:'自动打卡',heroDescription:'保存资料，导入课表，自动绑定后启用。',
    profileHeading:'学生资料',openSubscription:'订阅手机提醒',profileSummaryEmpty:'填写学号与姓名',studentId:'学号',studentName:'姓名',studentType:'学生身份',studentGroup:'课表组别',groupAny:'不筛选',localStudent:'本地学生',internationalStudent:'国际学生',saveProfile:'保存资料',chromeLoginHint:'请在当前 Chrome 用户中登录学校 Microsoft 账号。',
    timetableHeading:'课表',timetableDescription:'直接删除不需要的课程；展开可修改。',clearDraft:'清空草稿',importTimetable:'导入课表',addCourse:'添加课程',timetableHint:'支持 JPG、PNG、PDF。选择组别后，只过滤明确标记为其他组的 Lab；其他课程和无法识别组别的课程会保留。',noTimetable:'还没有导入课表。',draftAutoSave:'草稿自动保存，启用后才会执行。',bindingHeading:'表单绑定',bindingDescription:'粘贴链接或上传二维码即可自动绑定；扫描不会提交表单。',clearBindings:'清空绑定',emptyBindings:'先导入或添加课程。',tasksHeading:'每周任务',tasksDescription:'结束前 5 分钟自动执行。请保持 Chrome 运行、电脑清醒且学校账号已登录。',clearTasks:'删除全部任务',
    recordsHeading:'打卡记录',recordsMeta:'查看结果与导出',filterRecords:'筛选结果',filterAll:'全部结果',filterUnknown:'结果不明',filterFailed:'失败',filterMissed:'未自动提交',filterSuccess:'成功',exportRecords:'导出记录',previousPage:'上一页',nextPage:'下一页',
    workflowLabel:'导航与操作',workflowToggle:'操作',pageNavigation:'页面导航',navTimetable:'课表',navBindings:'表单绑定',navTasks:'每周任务',navProfile:'学生资料',reviewDraft:'我已核对课表与组别。',verifyAllForms:'自动扫描并保存全部',testAllForms:'测试全部课型 · 不提交',confirmAllForms:'一键确认全部课型',enableTasks:'启用每周任务',cancelChecks:'取消检查',
    profileSavedSummary:'资料已保存 · 展开修改',profileSavedToast:'学生资料已保存。',profileInvalid:'请先填写有效学号和姓名。',emptyAgendaTitle:'等待你的课表',emptyAgendaCopy:'上传文件后，这里会按星期列出课程。',emptyAgenda:'还没有待核对的课程。也可以先手动添加一节。',previewCount:'{count} 节待核对课程',previewDayCount:'分为 {count} 个上课日 · 展开课程可修改星期与时间',weekdayPrefix:'每',weekdayFallback:'周一',lessonCount:'{count} 节课',endTimeSuffix:'结束',everyWeek:'每周重复',unnamedCourse:'未命名课程',coursePlaceholder:'课程名',fieldCourseName:'课程名称',fieldWeekday:'每周星期',fieldStartTime:'开始时间',fieldEndTime:'结束时间',fieldExceptions:'停课日期（可选，多个日期用逗号分隔）',delete:'删除',
    clearPreviewConfirm:'清空待核对课表？已启用的每周任务会保留。',clearBindingsConfirm:'清空全部课程绑定？重新绑定前无法自动提交。',clearTasksConfirm:'删除全部每周任务？打卡记录会保留。',draftCleared:'课表草稿已清空。',bindingsCleared:'课程绑定已清空。',tasksDeleted:'每周任务已删除。',
    emptyTasks:'还没有任务。完成表单检查后，启用已核对的草稿。',inspectFormsCopy:'共用此链接：{courses}',formsUrlPlaceholder:'粘贴 Forms 链接，或上传二维码',formsUrlLabel:'{key} Microsoft Forms 链接',uploadQr:'上传二维码',bindingReady:'已核对：{title}',legacyConflict:'旧版课型绑定了不同链接。请使用这一门课程共用的链接重新核对。',bindingNeedsReview:'粘贴链接或上传二维码，自动扫描并保存。',qrRead:'二维码已读取。点击底部“一键打开全部并核对”继续。',
    boundSuccessfully:'✅ 绑定成功',dateOptional:'日期为选填 · 自动跳过',readingQr:'正在读取二维码…',noFormLinks:'请先粘贴表单链接或上传二维码。',scanCancelled:'链接已变化，已取消旧扫描。',scanningAll:'正在扫描并保存…',scanSummary:'已绑定 {succeeded} 门课程；{failed} 门需处理。',inspectionBusy:'正在读取表单，请先完成当前核对后再继续。',openingForm:'正在后台扫描并保存表单…',inspectionTimeout:'未能读取表单。请检查学校登录状态后重试。',openedForms:'已同时打开 {count} 个课程表单，请分别核对并保存。',actualForm:'实际表单：{title} · {url}',courseCodeMissing:'注意：表单标题中未找到课程代码 {code}，请仔细核对。',editMapping:'查看或修改题目匹配',bindingConfirmation:'我已核对：这是 {key} 的共用打卡表单，适用于 {courses}。',saveBinding:'保存表单绑定',verifyBeforeSave:'请先核对课程与表单。',mapEveryQuestion:'请为每一道题选择对应资料。',verifiedForm:'已核对：{title}',bindingSaved:'{key} 共用表单已绑定。',formsNotFound:'没有找到可配置的 Microsoft Forms 答题页。',reviewForm:'请核对表单标题与每道题，再保存绑定。',
    recognizingTimetable:'正在本机识别…',noRecognizedLessons:'没有可靠识别出课程。请手动添加，或上传更清晰的课表。',recognizedLessons:'识别出 {count} 行。{groupWarning}请逐行核对，再绑定二维码。',groupWarning:'可在学生资料中选择自己的组别，自动过滤明确标记为其他组的 Lab；无法识别组别的课程会保留。',groupFilterSummary:'已选择 Group {group}，过滤了 {count} 个其他组 Lab；无法识别组别的课程已保留。',noMatchingGroupLessons:'所选 Group {group} 下没有可导入的课程。请检查组别，或改为“不筛选”。',noImportYet:'还没有导入课表。',
    savingDraftFailed:'草稿保存失败：{error}',draftSavedNeedsReview:'草稿已在本机自动保存；重新核对后勾选确认。保存草稿不会启用任务。',draftRestored:'已恢复本机草稿；保存草稿不会启用任务。',draftReviewed:'课表已核对，表单绑定后即可启用。',draftUnreviewed:'草稿已保存，尚未核对。',taskEnabledDraft:'任务已启用；可导入或添加新的课程。',draftReadyToRun:'课表已核对，表单绑定后即可启用。',
    noTasks:'还没有任务。完成表单检查后，启用已核对的草稿。',sessionSummary:'每周{weekday} {start}–{end} · {state} · {check}',paused:'已暂停',nextRun:'下次：{date}（马来西亚）',noNextRun:'暂未找到下次触发',checksComplete:'已自动绑定',checksIncomplete:'需要绑定表单',enable:'启用',pause:'暂停',editSession:'编辑星期、时间与停课日期',fieldCourse:'课程名称',fieldExceptionsShort:'停课日期（用逗号分隔）',saveChanges:'保存修改',noSuchTask:'任务已删除。',checkBeforeEnable:'请先绑定此课程表单，再启用。',duplicateTask:'相同课程与时间的任务已存在。',taskSavedRemovedTrigger:'任务修改已保存，旧时间的触发已移除。',savedPausedForReview:'修改已保存并暂停；绑定表单后即可启用。',
    setupReadyTitle:'全部课型已填写完成，可一键确认；不会提交表单。',setupFailedTitle:'有课型检查失败，请先取消检查，再重新测试。',setupWaitingTitle:'等待全部 Forms 检查页完成填写；确认后不会提交表单。',recordCount:'{count} 条记录',lessonFallback:'课程',recordSuccess:'成功',recordUnknown:'结果不明',recordSubmittedPending:'已提交，待确认',recordFailed:'失败',recordMissed:'未自动提交',recordMissedSleep:'已错过（设备休眠）',recordLaunched:'打开中',recordPending:'提交中',markSubmitted:'标记为已提交',allowResubmit:'允许重新提交',allowResubmitConfirm:'这可能造成重复打卡。仅在你确认学校记录未提交时继续，且系统不会自动重试。确定解除保护吗？',resubmitProtectionReleased:'已解除提交保护；系统不会自动重新提交。',noOriginalForm:'尚无原表单链接，请先修复课程表单绑定。',noRecords:'还没有打卡记录。',noFilteredRecords:'没有此类型的记录，请调整筛选。',recordsPage:'第 {page} / {pages} 页 · {count} 条',
    noPreviewToActivate:'请先导入或添加课程。',draftChangedReview:'课表已变化，请重新核对并勾选确认。',reviewBeforeEnable:'请先核对课表，再勾选确认。',saveProfileFirst:'请先保存修改后的学生资料。',confirmLessonTypes:'请先检查并确认这些课型：{courses}。',enabledWeeklyTasks:'每周任务已启用。',enabledReviewedDraft:'已启用之前核对的课表；新修改已保留为草稿。',checksOpened:'已打开各课型的检查页{count}，填写后请在各页面确认；不会提交。',checksPageCount:'，共 {count} 页',allChecksConfirmed:'已一键确认全部 {count} 个课型，未提交表单。现在可以启用每周任务。',
    importerQrImage:'请上传二维码图片（PNG 或 JPG）。',importerQrUnread:'未能从图片中识别二维码，请换清晰截图或粘贴链接。',importerRecognizeHeader:'正在识别课表的日期、时间和星期',importerGridFallback:'表格网格校验未通过（{reason}），正在尝试整图 OCR。识别结果需要人工核对。',gridFallbackNotice:'网格校验未通过，当前内容来自整图 OCR；请核对课程、星期和时间。',importerFileLimit:'请选择不超过 20 MB 的 JPG、PNG 或 PDF。',importerPdfPages:'PDF 最多支持 20 页。',importerReadingPage:'正在读取 PDF 第 {page}/{pages} 页',importerOcrPage:'第 {page} 页需要本机 OCR 识别',importerOcrImage:'正在本机 OCR 识别图片',importerUnsupported:'课表只支持 JPG/JPEG、PNG 或 PDF。',
    dateAutoCheck:'当日日期 · 自动核对',profileFieldStudent:'学号',profileFieldName:'姓名',dateMismatchQuestion:'日期题型不匹配，请核对表单',selectTextData:'选择文字资料',courseKindAuto:'按课程名称自动选',unsupportedCourseOptions:'课程类型选项不受支持',studentTypeAuto:'按学生身份自动选 Local / International',unsupportedQuestion:'暂不支持这道题',fixedOption:'固定选 {option}',fixedLocal:'固定选 Local',fixedInternational:'固定选 International',
    recoveryInspect:'手动核对原表单',recoveryInspectDescription:'已开始提交但结果不明。请手动核对学校记录；系统不会自动重试。',recoverySubmittedPending:'我要手动检查',recoverySubmittedPendingDescription:'已点击提交但尚未确认。请检查学校记录；系统不会重复提交。',recoveryBinding:'修复课程表单绑定',recoveryBindingDescription:'重新核对表单和资料映射，再运行设置检查。',recoveryLogin:'检查学校登录与表单',recoveryLoginDescription:'打开原表单检查学校登录、开放时间或额外验证。',recoveryMissed:'打开表单手动处理',recoveryMissedDescription:'此次未自动提交。请按学校要求手动处理，并检查 Chrome 与电脑休眠设置。',recoveryView:'查看原表单',recoverySuccessDescription:'原表单已显示成功反馈。',recoveryCurrentDescription:'请查看当前运行页面。',
    subscriptionTitle:'手机提醒订阅',subscriptionMeta:'可选 · 展开购买或激活',subscriptionIntro:'购买后用密钥激活；本机自动打卡无需手机提醒授权。',chooseCurrency:'选择货币',
    planName:'手机提醒续订',planDescription:'续订后，服务有效期至密钥对应的学期截止日。',pricePeriod:'/sem',purchaseRm:'获取授权密钥',purchaseRmb:'前往店铺 · 手机提醒续订',
    activationHeading:'首次激活新密钥或续期',newKey:'新密钥',activate:'激活手机提醒',refresh:'刷新授权',entitlementLoading:'展开后查询手机提醒授权。',
    recoveryTitle:'已兑换过密钥？恢复手机提醒',recoveryDescription:'输入之前兑换过的原密钥，验证码会发送到原来接收提醒的手机。恢复不会再次兑换密钥；如果电脑上的本地资料也已清除，请重新导入课表并填写学生资料。',
    oldKey:'已兑换的原密钥',sendCode:'发送验证码',receivedCode:'手机收到的 6 位验证码',verifyRecover:'验证并恢复',cancelRecovery:'取消恢复',
    subscriptionHelp:'订阅说明',subscriptionTerms:'每把密钥只能绑定一台设备。同一学期的密钥不叠加时长；学期截止日按马来西亚时间当天结束计算。ntfy 主题不能代替有效授权。',phoneStatusTitle:'连接手机与通知状态',cloudStarting:'正在准备云端连接…',topicStarting:'手机主题尚未准备。',retryConnection:'重试连接',copyTopic:'复制 ntfy 地址',topicQr:'订阅二维码',choosePhoneSystem:'选择手机系统',androidSubscribe:'Android · 自动订阅',iosSubscribe:'iPhone / iPad',topicQrAccessible:'ntfy 订阅二维码',refreshDelivery:'刷新通知状态',queueStatus:'待同步 {count} 项',queueError:' · 最近错误：{error}',queueSent:' · 最近发送：{date}',connectionRestored:'设备连接已恢复。',waitingConnection:'等待连接。',topicNotReady:'手机主题尚未准备好，请重试云端连接。',copiedTopic:'已复制 ntfy 地址，请在手机 ntfy 中订阅。',qrAndroidHelp:'扫码会打开 ntfy 并自动订阅主题。ntfy 链接无法远程替你改 App 设置；扫码后请在 ntfy 设置中启用“即时交付 / Subscription Service”，并允许常驻通知。F-Droid 版默认使用即时交付。',qrIosHelp:'扫码会打开主题网页。iOS 请在 ntfy App 添加订阅（服务器 ntfy.sh，主题 {topic}），并在 iPhone“设置 > 通知 > ntfy”允许通知；如启用了专注模式或定时摘要，请允许 ntfy 通知通过专注模式，并将其从定时摘要中移除。iOS 没有 Android 的即时交付开关。',deliveryRecorded:'发送状态来自服务器；ntfy 接受不等于手机收到。',deliveryEmpty:'尚无云端通知记录。',receiptConfirmed:'学生已确认手机收到',deliveryQueued:'已排队',deliverySending:'正在发送',deliveryAccepted:'ntfy 已接受，手机收到尚未确认',deliveryUncertain:'发送结果不明，未自动重发',deliveryDiscarded:'未发送或已停止重试',confirmReceipt:'我已在手机看到这条消息',deliveryUnknown:'状态未知',
    noEntitlement:'当前没有手机提醒授权。购买套餐后，在下方输入密钥激活。',checkingEntitlement:'正在查询手机提醒授权…',entitlementActive:'授权有效',entitlementPending:'授权尚未开始',entitlementExpired:'授权已到期',entitlementRevoked:'授权已撤销',phonePlan:'手机提醒续期',firstTermPlan:'首学期套餐',semesterSubscriptionPlan:'学期订阅',phoneFallback:'手机提醒',unknownStatus:'状态未知',expiry:' · 学期截止：{date}',permissionOff:' · 手机提醒权限未开启',cloudConnected:'云端设备已连接；发送进度请查看队列与通知状态。',phoneTopicReady:'手机主题已准备（主题本身不包含授权）。在 ntfy 订阅',cloudFailed:'云端连接失败：{error}。本机自动打卡仍可使用。',recoverySendFailed:'暂时无法发送验证码，请检查网络后重试。',
    entitlementFailed:'暂时无法读取手机提醒授权，请检查网络后重试。',enterPurchaseKey:'请输入购买后收到的密钥。',activatingKey:'正在验证并激活密钥…',keyActivated:'密钥已激活，正在刷新授权状态。',activationFailed:'激活失败，请检查密钥和网络后重试。',
    errInvalidKey:'密钥无效，请检查后重试。',errKeyUsed:'这把密钥已经兑换过。',errKeyRevoked:'这把密钥已撤销，请联系店铺处理。',errKeyExpired:'这把密钥对应的学期已截止，无法激活。',errActivationFailed:'激活服务暂时不可用，请稍后重试。',errUnauthorized:'设备云端凭证已失效，请联系支持。已保留本机配置与设备身份；不会自动覆盖注册。',errDeviceExists:'该设备身份已存在，请联系支持恢复云端凭证。本机自动打卡仍可使用。',
    recoveryUnavailable:'无法验证这把密钥或联系原手机通知。请核对密钥；若仍无法恢复，请联系店铺支持。',recoveryDeliveryFailed:'验证码发送失败，请稍后重试。旧订阅凭证未更改。',recoveryRateLimited:'请求过于频繁，请稍后再试。',recoveryCodeInvalid:'验证码不正确，请核对手机上的最新消息后再试。',recoveryCodeExpired:'验证码已过期，请重新发送。',recoveryAttemptsExhausted:'尝试次数已用完，请重新发送验证码。',
    recoveryChoice:'请先恢复已购买的订阅，或使用新密钥激活手机提醒。',recoveryOutcomeUnknown:'恢复请求结果尚未确认。请使用原验证码再次验证，不要取消恢复。',recoveryInProgress:'恢复正在处理中，请勿取消。',
    recoveryUnknownStatus:'暂时无法确认恢复结果。请使用原验证码再次验证，不要取消流程。',enterOldKey:'请输入已兑换过的原密钥。',sendingCode:'正在发送…',resendAfter:'{seconds} 秒后可重发',resendCode:'重新发送验证码',sendingRecovery:'正在向原手机通知发送验证码…',recoveryPending:'恢复结果暂未确认。请使用原验证码继续验证；请勿取消流程或改用新密钥。',
    sentCode:'验证码已发送到原来接收手机提醒的应用，有效至 {time}。',expiredCode:'上次验证码已过期，请重新发送。',requestUnconfirmed:'上次发送请求未完成确认；可重新请求验证码。',recoveryIncomplete:'恢复尚未完成，可以重新请求验证码，或取消这次恢复。',enterSixDigits:'请输入手机收到的 6 位验证码。',verifyingRecover:'正在验证并恢复订阅…',recoverySuccess:'订阅恢复成功。正在更新授权与通知状态。',recoveryCancelled:'恢复流程已取消，原订阅凭证未更改。',cancelFailed:'暂时无法取消，请刷新页面后重试。',
  },
  en:{
    documentTitle:'Attendance · Auto-Check Settings',appTitle:'Auto-Check',heroDescription:'Save your profile, import your timetable, auto-bind your forms, and enable check-ins.',
    profileHeading:'Student profile',openSubscription:'Phone notifications',profileSummaryEmpty:'Enter your student ID and name',studentId:'Student ID',studentName:'Name',studentType:'Student type',studentGroup:'Timetable group',groupAny:'Do not filter',localStudent:'Local student',internationalStudent:'International student',saveProfile:'Save profile',chromeLoginHint:'Sign in to your school Microsoft account in this Chrome profile.',
    timetableHeading:'Timetable',timetableDescription:'Delete lessons you do not need; expand a lesson to edit it.',clearDraft:'Clear draft',importTimetable:'Import timetable',addCourse:'Add lesson',timetableHint:'JPG, PNG, and PDF supported. When a group is selected, only Lab sessions clearly assigned to other groups are filtered; other and unknown-group sessions stay for review.',noTimetable:'No timetable imported yet.',draftAutoSave:'Drafts save automatically and run only after you enable them.',bindingHeading:'Form bindings',bindingDescription:'Paste a link or upload a QR code to bind automatically. Scans never submit forms.',clearBindings:'Clear bindings',emptyBindings:'Import or add a lesson first.',tasksHeading:'Weekly tasks',tasksDescription:'Runs 5 minutes before each lesson ends. Keep Chrome running, your computer awake, and your school account signed in.',clearTasks:'Delete all tasks',
    recordsHeading:'Check-in records',recordsMeta:'Review results and export',filterRecords:'Filter results',filterAll:'All results',filterUnknown:'Unknown',filterFailed:'Failed',filterMissed:'Not submitted automatically',filterSuccess:'Succeeded',exportRecords:'Export records',previousPage:'Previous page',nextPage:'Next page',
    workflowLabel:'Navigation and actions',workflowToggle:'Actions',pageNavigation:'Page navigation',navTimetable:'Timetable',navBindings:'Form bindings',navTasks:'Weekly tasks',navProfile:'Student profile',reviewDraft:'I reviewed the timetable and groups.',verifyAllForms:'Auto-Scan & Save All',testAllForms:'Check all form types · No submission',confirmAllForms:'Confirm all form types',enableTasks:'Enable weekly tasks',cancelChecks:'Cancel checks',
    profileSavedSummary:'Saved profile · Expand to edit',profileSavedToast:'Student profile saved.',profileInvalid:'Enter a valid student ID and name first.',emptyAgendaTitle:'Your timetable will appear here',emptyAgendaCopy:'Import a file to list lessons by weekday.',emptyAgenda:'No lessons to review yet. You can also add one manually.',previewCount:'{count} lesson(s) to review',previewDayCount:'Across {count} weekdays · Expand a lesson to edit its day or time',weekdayPrefix:'Every ',weekdayFallback:'Monday',lessonCount:'{count} lesson(s)',endTimeSuffix:'end',everyWeek:'Repeats weekly',unnamedCourse:'Untitled lesson',coursePlaceholder:'Lesson name',fieldCourseName:'Course name',fieldWeekday:'Weekday',fieldStartTime:'Start time',fieldEndTime:'End time',fieldExceptions:'No-class dates (optional, comma-separated)',delete:'Delete',
    clearPreviewConfirm:'Clear the timetable draft? Enabled weekly tasks will remain.',clearBindingsConfirm:'Clear all course bindings? Automatic submission will pause until they are rebound.',clearTasksConfirm:'Delete all weekly tasks? Check-in records will remain.',draftCleared:'Timetable draft cleared.',bindingsCleared:'Course bindings cleared.',tasksDeleted:'Weekly tasks deleted.',
    emptyTasks:'No tasks yet. Check the forms, then enable the reviewed draft.',inspectFormsCopy:'Shared by: {courses}',formsUrlPlaceholder:'Paste a Forms link or upload a QR code',formsUrlLabel:'{key} Microsoft Forms link',uploadQr:'Upload QR code',bindingReady:'Verified: {title}',legacyConflict:'Old form types use different links. Recheck them using one shared link for this course.',bindingNeedsReview:'Paste a link or upload a QR code to scan and save automatically.',qrRead:'QR code read. Use “Open and review all forms” in the bottom controls to continue.',
    boundSuccessfully:'✅ Bound successfully',dateOptional:'Optional Date · skipped',readingQr:'Reading QR code…',noFormLinks:'Paste a form link or upload a QR code first.',scanCancelled:'Link changed; previous scan cancelled.',scanningAll:'Scanning & saving…',scanSummary:'Bound {succeeded} subject(s); {failed} need attention.',inspectionBusy:'Forms are being read. Finish the current review before continuing.',openingForm:'Scanning and saving the form in the background…',inspectionTimeout:'Could not read the form. Check your school sign-in and try again.',openedForms:'Opened {count} course form(s). Review and save each one.',actualForm:'Form found: {title} · {url}',courseCodeMissing:'The form title does not contain course code {code}. Check it carefully.',editMapping:'View or edit question mappings',bindingConfirmation:'I confirmed this shared check-in form is for {key} and applies to {courses}.',saveBinding:'Save form binding',verifyBeforeSave:'Confirm the course and form first.',mapEveryQuestion:'Choose a profile field for every question.',verifiedForm:'Verified: {title}',bindingSaved:'Shared form bound to {key}.',formsNotFound:'No configurable Microsoft Forms response page was found.',reviewForm:'Review the form title and every question, then save the binding.',
    recognizingTimetable:'Reading timetable on this device…',noRecognizedLessons:'No lessons could be reliably recognized. Add them manually or upload a clearer timetable.',recognizedLessons:'Recognized {count} row(s). {groupWarning}Review each row, then bind its QR code.',groupWarning:'Choose your group in Student profile to filter out clearly marked Lab sessions from other groups. Unknown groups are kept for review. ',groupFilterSummary:'Group {group} selected; filtered out {count} Lab session(s) from other groups. Unknown groups are kept for review.',noMatchingGroupLessons:'No courses remain for Group {group}. Check the selected group or choose “Do not filter”.',noImportYet:'No timetable imported yet.',
    savingDraftFailed:'Could not save the draft: {error}',draftSavedNeedsReview:'Draft saved on this device. Review it again and confirm before continuing. Saving a draft does not enable tasks.',draftRestored:'Restored the local draft. Saving a draft does not enable tasks.',draftReviewed:'Timetable reviewed. Bind the forms to enable tasks.',draftUnreviewed:'Draft saved but not reviewed.',taskEnabledDraft:'Tasks enabled. You can import or add more lessons.',draftReadyToRun:'Timetable reviewed. Bind the forms to enable tasks.',
    noTasks:'No tasks yet. Check the forms, then enable the reviewed draft.',sessionSummary:'Every {weekday} {start}–{end} · {state} · {check}',paused:'Paused',nextRun:'Next: {date} (Malaysia time)',noNextRun:'No upcoming run found',checksComplete:'Form bound',checksIncomplete:'Form binding needed',enable:'Enable',pause:'Pause',editSession:'Edit weekday, time, and no-class dates',fieldCourse:'Course name',fieldExceptionsShort:'No-class dates (comma-separated)',saveChanges:'Save changes',noSuchTask:'This task was deleted.',checkBeforeEnable:'Bind this course’s form before enabling it.',duplicateTask:'A task for the same course and time already exists.',taskSavedRemovedTrigger:'Task updated; the old scheduled trigger was removed.',savedPausedForReview:'Changes saved and task paused. Bind the form before enabling it.',
    setupReadyTitle:'All form types are filled in and ready to confirm. No form will be submitted.',setupFailedTitle:'A form check failed. Cancel the check, then run it again.',setupWaitingTitle:'Waiting for all Forms pages to finish filling. Confirmation will not submit any form.',recordCount:'{count} record(s)',lessonFallback:'Lesson',recordSuccess:'Succeeded',recordUnknown:'Unknown',recordSubmittedPending:'Submitted, awaiting confirmation',recordFailed:'Failed',recordMissed:'Not submitted automatically',recordMissedSleep:'Missed because the device slept',recordLaunched:'Opening',recordPending:'Submitting',markSubmitted:'Mark as submitted',allowResubmit:'Allow resubmission',allowResubmitConfirm:'This may cause a duplicate check-in. Continue only if you confirmed the school record was not submitted; the system will not retry automatically. Release the protection?',resubmitProtectionReleased:'Submission protection released; the system will not submit automatically.',noOriginalForm:'No original form link is saved. Repair the course binding first.',noRecords:'No check-in records yet.',noFilteredRecords:'No records match this filter.',recordsPage:'Page {page} of {pages} · {count} item(s)',
    noPreviewToActivate:'Import or add a lesson first.',draftChangedReview:'The timetable changed. Review it again and confirm.',reviewBeforeEnable:'Review the timetable, then check the confirmation box.',saveProfileFirst:'Save your changed student profile first.',confirmLessonTypes:'Check and confirm these form types first: {courses}.',enabledWeeklyTasks:'Weekly tasks enabled.',enabledReviewedDraft:'Enabled the reviewed timetable. New changes remain saved as a draft.',checksOpened:'Opened the form-type checks{count}. Review each page; nothing will be submitted.',checksPageCount:' ({count} page(s))',allChecksConfirmed:'Confirmed all {count} form types without submitting. You can now enable weekly tasks.',
    importerQrImage:'Upload a QR code image (PNG or JPG).',importerQrUnread:'Could not read a QR code from this image. Use a clearer image or paste the link.',importerRecognizeHeader:'Recognizing timetable dates, times, and weekdays',importerGridFallback:'Grid validation failed ({reason}); trying full-page OCR. Review the result before enabling tasks.',gridFallbackNotice:'Grid validation failed; this row came from full-page OCR. Review the course, day, and time.',importerFileLimit:'Choose a JPG, PNG, or PDF no larger than 20 MB.',importerPdfPages:'PDFs are limited to 20 pages.',importerReadingPage:'Reading PDF page {page}/{pages}',importerOcrPage:'Page {page} needs on-device OCR',importerOcrImage:'Recognizing image with on-device OCR',importerUnsupported:'Timetables must be JPG/JPEG, PNG, or PDF.',
    dateAutoCheck:'Today’s date · verify automatically',profileFieldStudent:'Student ID',profileFieldName:'Name',dateMismatchQuestion:'Date question type mismatch. Check the form.',selectTextData:'Choose a profile field',courseKindAuto:'Choose automatically from course name',unsupportedCourseOptions:'Unsupported lesson type options',studentTypeAuto:'Choose automatically from student type',unsupportedQuestion:'This question type is not supported',fixedOption:'Select {option}',fixedLocal:'Select Local',fixedInternational:'Select International',
    recoveryInspect:'Check original form manually',recoveryInspectDescription:'Submission started but the result is unknown. Check the school record manually; the system will not retry.',recoverySubmittedPending:'I will check manually',recoverySubmittedPendingDescription:'Submission was clicked but not confirmed. Check the school record; the system will not submit again.',recoveryBinding:'Repair course form binding',recoveryBindingDescription:'Review the form and profile mappings, then run the setup check again.',recoveryLogin:'Check school sign-in and form',recoveryLoginDescription:'Open the original form and check your school sign-in, its open period, or any extra verification.',recoveryMissed:'Open form and handle manually',recoveryMissedDescription:'This check-in was not submitted automatically. Follow your school’s instructions and check Chrome and sleep settings.',recoveryView:'View original form',recoverySuccessDescription:'The original form showed a success message.',recoveryCurrentDescription:'Check the currently open page.',
    subscriptionTitle:'Phone notification subscription',subscriptionMeta:'Optional · Expand to purchase or activate',subscriptionIntro:'Activate with a key after purchase. Local automatic check-ins do not require phone notification access.',chooseCurrency:'Choose currency',
    planName:'Phone notification renewal',planDescription:'After renewal, service remains valid until the semester end date assigned to the key.',pricePeriod:'/sem',purchaseRm:'Get License Key',purchaseRmb:'Go to store · Phone notification renewal',
    activationHeading:'Activate a new key or renew',newKey:'New key',activate:'Activate phone notifications',refresh:'Refresh authorization',entitlementLoading:'Expand to check phone notification authorization.',
    recoveryTitle:'Already redeemed a key? Restore phone notifications',recoveryDescription:'Enter the original key you redeemed before. A verification code will be sent to the phone that receives your reminders. Recovery does not redeem the key again. If your local computer data was also cleared, import your timetable and enter your student details again.',
    oldKey:'Previously redeemed key',sendCode:'Send code',receivedCode:'6-digit code from your phone',verifyRecover:'Verify and restore',cancelRecovery:'Cancel recovery',
    subscriptionHelp:'Subscription details',subscriptionTerms:'Each key can be bound to one device. Keys for the same semester do not stack. The semester end date is inclusive in Malaysia time. An ntfy topic does not replace an active authorization.',phoneStatusTitle:'Phone and notification status',cloudStarting:'Preparing cloud connection…',topicStarting:'Phone topic is not ready yet.',retryConnection:'Retry connection',copyTopic:'Copy ntfy address',topicQr:'Subscription QR code',choosePhoneSystem:'Choose phone platform',androidSubscribe:'Android · Subscribe automatically',iosSubscribe:'iPhone / iPad',topicQrAccessible:'ntfy subscription QR code',refreshDelivery:'Refresh notification status',queueStatus:'{count} item(s) waiting to sync',queueError:' · Latest error: {error}',queueSent:' · Last sent: {date}',connectionRestored:'Device connection restored.',waitingConnection:'Waiting for connection.',topicNotReady:'Phone topic is not ready. Retry the cloud connection.',copiedTopic:'ntfy address copied. Subscribe to it in the ntfy app on your phone.',qrAndroidHelp:'Scanning opens ntfy and subscribes to the topic. An ntfy link cannot change app settings remotely; after scanning, enable “Instant Delivery / Subscription Service” in ntfy settings and allow persistent notifications. Instant delivery is enabled by default in the F-Droid version.',qrIosHelp:'Scanning opens the topic webpage. In the ntfy app on iOS, add a subscription (server ntfy.sh, topic {topic}), then allow notifications in iPhone Settings > Notifications > ntfy. If Focus or Scheduled Summary is enabled, allow ntfy through Focus and remove it from Scheduled Summary. iOS has no Android instant-delivery switch.',deliveryRecorded:'Delivery status comes from the server; ntfy acceptance does not confirm phone receipt.',deliveryEmpty:'There are no cloud notification records yet.',receiptConfirmed:'Student confirmed receipt on phone',deliveryQueued:'Queued',deliverySending:'Sending',deliveryAccepted:'Accepted by ntfy; phone receipt is not confirmed',deliveryUncertain:'Delivery is uncertain; it was not retried automatically',deliveryDiscarded:'Not sent or retries stopped',confirmReceipt:'I saw this message on my phone',deliveryUnknown:'Unknown status',
    noEntitlement:'There is no phone notification authorization yet. Purchase a plan, then enter your key below to activate it.',checkingEntitlement:'Checking phone notification authorization…',entitlementActive:'Authorization active',entitlementPending:'Authorization has not started',entitlementExpired:'Authorization expired',entitlementRevoked:'Authorization revoked',phonePlan:'Phone notification renewal',firstTermPlan:'First semester plan',semesterSubscriptionPlan:'Semester subscription',phoneFallback:'Phone notifications',unknownStatus:'Unknown status',expiry:' · Semester ends: {date}',permissionOff:' · Phone notifications are not enabled',cloudConnected:'Cloud device connected. Check the queue and notification status for delivery progress.',phoneTopicReady:'Phone topic is ready (the topic does not include authorization). Subscribe in ntfy:',cloudFailed:'Cloud connection failed: {error}. Local automatic check-ins are still available.',recoverySendFailed:'Could not send a verification code. Check your connection and try again.',
    entitlementFailed:'Could not load phone notification authorization. Check your connection and try again.',enterPurchaseKey:'Enter the key you received after purchase.',activatingKey:'Verifying and activating key…',keyActivated:'Key activated. Refreshing authorization status.',activationFailed:'Activation failed. Check the key and your connection, then try again.',
    errInvalidKey:'Invalid key. Check it and try again.',errKeyUsed:'This key has already been redeemed.',errKeyRevoked:'This key was revoked. Contact the store for help.',errKeyExpired:'The semester assigned to this key has ended; it cannot be activated.',errActivationFailed:'The activation service is temporarily unavailable. Try again later.',errUnauthorized:'The device cloud credential is no longer valid. Contact support. Your local settings and device identity are preserved; registration will not be overwritten.',errDeviceExists:'This device identity already exists. Contact support to restore cloud access. Local automatic check-ins are still available.',
    recoveryUnavailable:'Could not verify this key or contact the original phone notification. Check the key; if recovery still fails, contact store support.',recoveryDeliveryFailed:'Could not send the verification code. Try again later. The old subscription credentials are unchanged.',recoveryRateLimited:'Too many requests. Try again later.',recoveryCodeInvalid:'The code is incorrect. Check the latest message on your phone and try again.',recoveryCodeExpired:'The code expired. Send a new one.',recoveryAttemptsExhausted:'No attempts remain. Send a new verification code.',
    recoveryChoice:'Restore your purchased subscription first, or activate phone notifications with a new key.',recoveryOutcomeUnknown:'The recovery request is not confirmed yet. Verify again with the original code; do not cancel recovery.',recoveryInProgress:'Recovery is in progress. Do not cancel it.',
    recoveryUnknownStatus:'Could not confirm the recovery result. Verify again with the original code; do not cancel the process.',enterOldKey:'Enter the key you redeemed before.',sendingCode:'Sending…',resendAfter:'Resend in {seconds}s',resendCode:'Resend code',sendingRecovery:'Sending a verification code to the original phone notification…',recoveryPending:'Recovery is not confirmed yet. Continue with the original code; do not cancel or switch to a new key.',
    sentCode:'A code was sent to the app that receives your phone reminders. It is valid until {time}.',expiredCode:'The last code expired. Send a new one.',requestUnconfirmed:'The previous send request was not confirmed. You can request another code.',recoveryIncomplete:'Recovery is not complete. Request another code or cancel this recovery.',enterSixDigits:'Enter the 6-digit code from your phone.',verifyingRecover:'Verifying and restoring subscription…',recoverySuccess:'Subscription restored. Updating authorization and notification status.',recoveryCancelled:'Recovery cancelled. The original subscription credentials are unchanged.',cancelFailed:'Could not cancel right now. Refresh the page and try again.',
  },
};

let language='zh';
export function t(key,values={}) {
  const template=copy[language][key]??copy.zh[key]??key;
  return template.replace(/\{(\w+)\}/g,(_,name)=>values[name]??'');
}
const errorText={
  '二维码或链接不是有效网址。':'The QR code or link is not a valid URL.','只接受 Microsoft Forms 的填写链接。':'Only Microsoft Forms response links are accepted.','表单链接缺少 ID。':'The Forms link is missing its ID.','无法识别表单日期格式。':'Could not recognize the date format in the form.','无法判断此课程类型，请选择 Lecture、Tutorial 或 Laboratory。':'Could not determine this lesson type. Choose Lecture, Tutorial, or Laboratory.',
  '表单题目发生变化，已停止。':'The form questions changed. Processing stopped.','任务日期与马来西亚当天日期不一致，已停止。':'The task date does not match today in Malaysia. Processing stopped.','电脑本地日期与马来西亚日期不一致，已停止。':'The computer date does not match the Malaysia date. Processing stopped.',
  '任务类型无效。':'Invalid task type.','每周星期须为 0–6 的整数。':'Weekday must be an integer from 0 to 6.','任务日期无效。':'Invalid task date.','停课日期格式无效。':'Invalid no-class date format.','任务启用状态无效。':'Invalid task enabled state.',
  '课程名称须为 2–64 个英文字母、数字、空格、下划线或连字符。':'Course names must contain 2–64 English letters, numbers, spaces, underscores, or hyphens.',
  '请先添加课程并核对表单绑定。':'Add a course and verify its form binding first.','一次最多检查 200 个表单课型。':'You can check up to 200 form types at a time.','检查已结束或页面不匹配。':'The check has ended or the page does not match.','无效的设置检查状态。':'Invalid setup check state.','检查未就绪或配置已变化，请重新检查。':'The check is not ready or the setup changed. Run the check again.',
  '不是支持的 Attendance 配置备份。':'This is not a supported Attendance configuration backup.','备份包含不支持的字段或凭证，未导入。':'The backup has unsupported fields or credentials and was not imported.','备份结构无效。':'Invalid backup structure.','备份学生资料无效。':'Invalid student profile in backup.','备份任务 ID 无效或重复。':'A backup task ID is invalid or duplicated.','备份任务包含不支持的状态。':'A backup task has an unsupported state.','备份绑定数量过多。':'The backup contains too many bindings.','备份表单绑定无效。':'Invalid form binding in backup.','备份绑定包含不支持的字段。':'A form binding in the backup contains unsupported fields.','备份表单题目无效。':'Invalid form questions in backup.','备份记录数量过多。':'The backup contains too many records.','备份只能包含有效的已结束记录。':'Backups can include only valid, completed records.','备份包含运行中状态，未导入。':'The backup includes an in-progress state and was not imported.',
};
export function localizeMessage(message) {
  if(language!=='en'||typeof message!=='string') return message;
  if(errorText[message]) return errorText[message];
  const patterns=[
    [/^课程名称须为 2–64 个英文字母、数字、空格、下划线或连字符。$/,'Course names must contain 2–64 English letters, numbers, spaces, underscores, or hyphens.'],
    [/^(.+) 需要重新读取并保存表单题目。$/,'Reload and save the form questions for $1.'],
    [/^(.+) 的起止时间无效。$/,'$1 has an invalid start or end time.'],[/^(.+) 的停课日期无效。$/,'$1 has an invalid no-class date.'],
    [/^第 (\d+) 题映射与题型不一致，未提交。$/,'Question $1 does not match its configured type. Nothing was submitted.'],
    [/^未配置第 (\d+) 题。$/,'Question $1 is not configured.'],[/^第 (\d+) 题没有匹配的答案。$/,'No answer matches question $1.'],
    [/^(.+) 尚未绑定并核对共用表单。$/,'$1 does not have a verified shared form.'],[/^(.+) 的固定课型与课程名称不一致，请重新核对共用表单。$/,'The fixed lesson type for $1 does not match its course name. Review the shared form again.'],
    [/^请先为 (.+) 配置表单题目。$/,'Configure the form questions for $1 first.'],
  ];
  for(const [pattern,replacement] of patterns) if(pattern.test(message)) return message.replace(pattern,replacement);
  return message;
}
export function currentLanguage() {return language;}
export async function setLanguage(value,persist=true) {
  language=value==='en'?'en':'zh';
  if(persist) await chrome.storage.local.set({attendanceLanguage:language});
  document.documentElement.lang=language==='en'?'en':'zh-CN';
  document.querySelectorAll('[data-i18n]').forEach(element=>{element.textContent=t(element.dataset.i18n);});
  document.querySelectorAll('[data-i18n-aria-label]').forEach(element=>{element.setAttribute('aria-label',t(element.dataset.i18nAriaLabel));});
  document.querySelectorAll('[data-i18n-placeholder]').forEach(element=>{element.setAttribute('placeholder',t(element.dataset.i18nPlaceholder));});
  document.querySelectorAll('[data-i18n-title]').forEach(element=>{element.setAttribute('title',t(element.dataset.i18nTitle));});
  document.querySelector('#language-en')?.setAttribute('aria-pressed',String(language==='en'));
  document.querySelector('#language-zh')?.setAttribute('aria-pressed',String(language==='zh'));
  document.querySelector('#language-en')?.classList.toggle('selected',language==='en');
  document.querySelector('#language-zh')?.classList.toggle('selected',language==='zh');
}
